# Generated by Django 5.1.2 on 2024-10-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='conteudo', max_length=2000),
            preserve_default=False,
        ),
    ]
